In [1]:
import os
from dotenv import load_dotenv
load_dotenv()

gemini_api_key = os.getenv("GEMINI_API_KEY")

In [2]:
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage

llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", google_api_key=gemini_api_key)

llm.invoke([HumanMessage("테슬라는 한달 전에 비해 주가가 올랐나 내렸나?")])

AIMessage(content="저는 실시간 주가 정보를 제공할 수 없습니다. 주가는 실시간으로 변동하기 때문에 정확한 정보를 위해서는 현재 시점의 데이터를 확인하셔야 합니다.\n\n테슬라(TSLA)의 한 달 전과 현재 주가를 비교하시려면 다음 사이트들을 참고하시면 좋습니다:\n\n*   **네이버 금융**\n*   **구글 금융**\n*   **야후 파이낸스**\n*   **증권사 앱/웹사이트**\n\n이러한 곳에서 'TSLA'를 검색하시면 현재 주가와 과거 주가 차트를 확인하실 수 있습니다.", additional_kwargs={}, response_metadata={'prompt_feedback': {'block_reason': 0, 'safety_ratings': []}, 'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash', 'safety_ratings': []}, id='run--157bd243-e5d2-47e8-befd-b2c8f618d625-0', usage_metadata={'input_tokens': 17, 'output_tokens': 969, 'total_tokens': 986, 'input_token_details': {'cache_read': 0}, 'output_token_details': {'reasoning': 842}})

### ⌚시계 도구

In [3]:
from langchain_core.tools import tool
from datetime import datetime
from zoneinfo import ZoneInfo

@tool # @tool 데코레이터를 사용하여 함수를 도구로 등록
def get_current_time(timezone: str, location: str) -> str:
    """ 현재 시각을 반환하는 함수

    Args:
        timezone (str): 타임존 (예: 'Asia/Seoul') 실제 존재하는 타임존이어야 함
        location (str): 지역명. 타임존이 모든 지명에 대응되지 않기 때문에 이후 llm 답변 생성에 사용됨
    """
    target_timezone = ZoneInfo(timezone)
    now = datetime.now(target_timezone).strftime("%Y-%m-%d %H:%M:%S")
    location_and_local_time = f'{timezone} ({location}) 현재시각 {now} ' # 타임존, 지역명, 현재시각을 문자열로 반환
    print(location_and_local_time)
    return location_and_local_time

#### 파이단틱(Pydantic)

*   **데이터 유효성 검사**: 런타임에 데이터 유효성을 강제하여 오류를 조기에 발견하고 안정적인 애플리케이션을 구축할 수 있게 한다. 
*   **설정 관리**: 환경 변수, 파일 등에서 애플리케이션 설정을 로드하고 유효성을 검사하여 안전하고 구성 가능한 애플리케이션을 만들 수 있게 한다.
*   **데이터 직렬화 및 역직렬화**: Python 객체를 JSON과 같은 형식으로 쉽게 변환(직렬화)하고 다시 Python 객체로 역변환(역직렬화)할 수 있게 한다.
*   **문서화**: Pydantic 모델은 OpenAPI(Swagger)와 같은 도구에서 자동으로 API 문서를 생성하는 데 사용될 수 있게 한다.

In [ ]:
from pydantic import BaseModel, Field

class StockHistoryInput(BaseModel):
    ticker: str = Field(..., title="주식 코드", description="주식 코드 (예: TSLA)")
    period: str = Field(..., title="기간", description="주식 데이터 조회 기간 (예: 1d, 1mo, 1y)")

#### Yahoo Finance API 간단 사용법

In [ ]:
import yfinance as yf

# 테슬라 주식 데이터 가져오기
tsla = yf.Ticker("TSLA")

# 1년간의 일별 주가 데이터
hist = tsla.history(period="1y")

In [10]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-09-10 00:00:00-04:00,220.070007,226.399994,218.639999,226.169998,78891100,0.0,0.0
2024-09-11 00:00:00-04:00,224.550003,228.470001,216.800003,228.130005,83548600,0.0,0.0
2024-09-12 00:00:00-04:00,224.660004,231.449997,223.830002,229.809998,71894900,0.0,0.0
2024-09-13 00:00:00-04:00,228.000000,232.669998,226.320007,230.289993,59515100,0.0,0.0
2024-09-16 00:00:00-04:00,229.300003,229.960007,223.529999,226.779999,54323000,0.0,0.0
...,...,...,...,...,...,...,...
2025-09-03 00:00:00-04:00,335.200012,343.329987,328.510010,334.089996,88733300,0.0,0.0
2025-09-04 00:00:00-04:00,336.149994,338.890015,331.480011,338.529999,60711000,0.0,0.0
2025-09-05 00:00:00-04:00,348.000000,355.869995,344.679993,350.839996,108989800,0.0,0.0
2025-09-08 00:00:00-04:00,354.640015,358.440002,344.839996,346.399994,75208300,0.0,0.0
2025-09-09 00:00:00-04:00,348.440002,350.769989,343.820007,346.970001,53689900,0.0,0.0

In [13]:
# 테슬라 주식 데이터 가져오기
tsla = yf.Ticker("TSLA")

# 특정 기간 (예: 2024년 1월 1일 ~ 2월 29일)
start_date = "2025-01-01"
end_date = "2025-01-31"
specific_hist = tsla.history(start=start_date, end=end_date)

In [14]:
specific_hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-01-02 00:00:00-05:00,390.100006,392.730011,373.040009,379.279999,109710700,0.0,0.0
2025-01-03 00:00:00-05:00,381.480011,411.880005,379.450012,410.440002,95423300,0.0,0.0
2025-01-06 00:00:00-05:00,423.200012,426.429993,401.700012,411.049988,85516500,0.0,0.0
2025-01-07 00:00:00-05:00,405.829987,414.329987,390.000000,394.359985,75699500,0.0,0.0
2025-01-08 00:00:00-05:00,392.950012,402.500000,387.399994,394.940002,73038800,0.0,0.0
2025-01-10 00:00:00-05:00,391.399994,399.279999,377.290009,394.739990,62287300,0.0,0.0
2025-01-13 00:00:00-05:00,383.209991,403.790009,380.070007,403.309998,67580500,0.0,0.0
2025-01-14 00:00:00-05:00,414.339996,422.640015,394.540009,396.359985,84565000,0.0,0.0
2025-01-15 00:00:00-05:00,409.899994,429.799988,405.660004,428.220001,81375500,0.0,0.0
2025-01-16 00:00:00-05:00,423.489990,424.000000,409.130005,413.820007,68335200,0.0,0.0
2025-01-17 00:00:00-05:00,421.500000,439.739990,419.750000,426.500000,94991400,0.0,0.0
2025-01-21 00:00:00-05:00,432.640015,433.200012,406.309998,424.070007,87320900,0.0,0.0
2025-01-22 00:00:00-05:00,416.809998,428.000000,414.589996,415.109985,60963300,0.0,0.0
2025-01-23 00:00:00-05:00,416.059998,420.730011,408.950012,412.380005,50690600,0.0,0.0
2025-01-24 00:00:00-05:00,414.450012,418.880005,405.779999,406.579987,56427100,0.0,0.0
2025-01-27 00:00:00-05:00,394.799988,406.690002,389.000000,397.149994,58125500,0.0,0.0
2025-01-28 00:00:00-05:00,396.910004,400.589996,386.500000,398.089996,48910700,0.0,0.0
2025-01-29 00:00:00-05:00,395.209991,398.589996,384.480011,389.100006,68033600,0.0,0.0
2025-01-30 00:00:00-05:00,410.779999,412.500000,384.410004,400.279999,98092900,0.0,0.0

In [18]:
print(specific_hist.to_markdown())

| Date                      |   Open |   High |    Low |   Close |      Volume |   Dividends |   Stock Splits |
|:--------------------------|-------:|-------:|-------:|--------:|------------:|------------:|---------------:|
| 2025-01-02 00:00:00-05:00 | 390.1  | 392.73 | 373.04 |  379.28 | 1.09711e+08 |           0 |              0 |
| 2025-01-03 00:00:00-05:00 | 381.48 | 411.88 | 379.45 |  410.44 | 9.54233e+07 |           0 |              0 |
| 2025-01-06 00:00:00-05:00 | 423.2  | 426.43 | 401.7  |  411.05 | 8.55165e+07 |           0 |              0 |
| 2025-01-07 00:00:00-05:00 | 405.83 | 414.33 | 390    |  394.36 | 7.56995e+07 |           0 |              0 |
| 2025-01-08 00:00:00-05:00 | 392.95 | 402.5  | 387.4  |  394.94 | 7.30388e+07 |           0 |              0 |
| 2025-01-10 00:00:00-05:00 | 391.4  | 399.28 | 377.29 |  394.74 | 6.22873e+07 |           0 |              0 |
| 2025-01-13 00:00:00-05:00 | 383.21 | 403.79 | 380.07 |  403.31 | 6.75805e+07 |           0 |              0 |
| 2025-01-14 00:00:00-05:00 | 414.34 | 422.64 | 394.54 |  396.36 | 8.4565e+07  |           0 |              0 |
| 2025-01-15 00:00:00-05:00 | 409.9  | 429.8  | 405.66 |  428.22 | 8.13755e+07 |           0 |              0 |
| 2025-01-16 00:00:00-05:00 | 423.49 | 424    | 409.13 |  413.82 | 6.83352e+07 |           0 |              0 |
| 2025-01-17 00:00:00-05:00 | 421.5  | 439.74 | 419.75 |  426.5  | 9.49914e+07 |           0 |              0 |
| 2025-01-21 00:00:00-05:00 | 432.64 | 433.2  | 406.31 |  424.07 | 8.73209e+07 |           0 |              0 |
| 2025-01-22 00:00:00-05:00 | 416.81 | 428    | 414.59 |  415.11 | 6.09633e+07 |           0 |              0 |
| 2025-01-23 00:00:00-05:00 | 416.06 | 420.73 | 408.95 |  412.38 | 5.06906e+07 |           0 |              0 |
| 2025-01-24 00:00:00-05:00 | 414.45 | 418.88 | 405.78 |  406.58 | 5.64271e+07 |           0 |              0 |
| 2025-01-27 00:00:00-05:00 | 394.8  | 406.69 | 389    |  397.15 | 5.81255e+07 |           0 |              0 |
| 2025-01-28 00:00:00-05:00 | 396.91 | 400.59 | 386.5  |  398.09 | 4.89107e+07 |           0 |              0 |
| 2025-01-29 00:00:00-05:00 | 395.21 | 398.59 | 384.48 |  389.1  | 6.80336e+07 |           0 |              0 |
| 2025-01-30 00:00:00-05:00 | 410.78 | 412.5  | 384.41 |  400.28 | 9.80929e+07 |           0 |              0 |

### 📈 주식 종목 가격 조회 도구

In [15]:
@tool
def get_yf_stock_history(stock_history_input: StockHistoryInput) -> str:
    """ 주식 종목의 가격 데이터를 조회하는 함수"""
    stock = yf.Ticker(stock_history_input.ticker)
    history = stock.history(period=stock_history_input.period)
    history_md = history.to_markdown() 

    return history_md

In [ ]:
from langchain.agents import AgentExecutor, create_tool_calling_agent
from langchain_core.prompts import ChatPromptTemplate

# 도구들을 tools 리스트에 추가
tools = [get_current_time, get_yf_stock_history]

# 에이전트 프롬프트 정의
prompt = ChatPromptTemplate.from_messages([
    ("system", "너는 사용자의 질문에 답변을 하기 위해 tools를 사용할 수 있다."),
    ("human", "{input}"),
    # AgentExecutor는 agent_scratchpad를 자동으로 채워 넣어,
    # 에이전트가 이전 단계의 행동과 결과를 기억하고 다음 행동을 결정할 수 있도록 함
    ("placeholder", "{agent_scratchpad}"),
])

# 에이전트 생성
agent = create_tool_calling_agent(llm, tools, prompt)

# AgentExecutor 초기화
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

In [ ]:
# 메시지 형식 변경 (agent_executor에 맞게)
messages = [
    HumanMessage("테슬라는 한달 전에 비해 주가가 올랐나 내렸나?"),
]

# agent_executor를 사용하여 실행
response = agent_executor.invoke({"input": messages})

> Entering new AgentExecutor chain...

Invoking: `get_yf_stock_history` with `{'stock_history_input': {'period': '1mo', 'ticker': 'TSLA'}}`


| Date                      |   Open |   High |    Low |   Close |      Volume |   Dividends |   Stock Splits |
|:--------------------------|-------:|-------:|-------:|--------:|------------:|------------:|---------------:|
| 2025-08-11 00:00:00-04:00 | 335    | 346.64 | 334.15 |  339.03 | 1.0532e+08  |           0 |              0 |
| 2025-08-12 00:00:00-04:00 | 345    | 345.26 | 332.94 |  340.84 | 8.05221e+07 |           0 |              0 |
| 2025-08-13 00:00:00-04:00 | 341.5  | 348.98 | 338.2  |  339.38 | 6.78389e+07 |           0 |              0 |
| 2025-08-14 00:00:00-04:00 | 335.76 | 340.47 | 330.4  |  335.58 | 7.50007e+07 |           0 |              0 |
| 2025-08-15 00:00:00-04:00 | 337.66 | 339.3  | 327.02 |  330.56 | 7.43198e+07 |           0 |              0 |
| 2025-08-18 00:00:00-04:00 | 329.62 | 336.27 | 329.59 |  335.16 | 5.69566e+07 |           0 |              0 |
| 2025-08-19 00:00:00-04:00 | 335.79 | 340.55 | 327.85 |  329.31 | 7.5956e+07  |           0 |              0 |
| 2025-08-20 00:00:00-04:00 | 329.22 | 331.37 | 314.6  |  323.9  | 7.74818e+07 |           0 |              0 |
| 2025-08-21 00:00:00-04:00 | 322.08 | 324.9  | 318.68 |  320.11 | 5.57444e+07 |           0 |              0 |
| 2025-08-22 00:00:00-04:00 | 321.66 | 340.25 | 319.69 |  340.01 | 9.40163e+07 |           0 |              0 |
| 2025-08-25 00:00:00-04:00 | 338.9  | 349.53 | 335.03 |  346.6  | 8.667e+07   |           0 |              0 |
| 2025-08-26 00:00:00-04:00 | 344.93 | 351.9  | 343.72 |  351.67 | 7.66516e+07 |           0 |              0 |
| 2025-08-27 00:00:00-04:00 | 351.94 | 355.39 | 349.16 |  349.6  | 6.5519e+07  |           0 |              0 |
| 2025-08-28 00:00:00-04:00 | 350.91 | 353.55 | 340.26 |  345.98 | 6.79032e+07 |           0 |              0 |
| 2025-08-29 00:00:00-04:00 | 347.23 | 348.75 | 331.7  |  333.87 | 8.11457e+07 |           0 |              0 |
| 2025-09-02 00:00:00-04:00 | 328.23 | 333.33 | 325.6  |  329.36 | 5.8392e+07  |           0 |              0 |
| 2025-09-03 00:00:00-04:00 | 335.2  | 343.33 | 328.51 |  334.09 | 8.87333e+07 |           0 |              0 |
| 2025-09-04 00:00:00-04:00 | 336.15 | 338.89 | 331.48 |  338.53 | 6.0711e+07  |           0 |              0 |
| 2025-09-05 00:00:00-04:00 | 348    | 355.87 | 344.68 |  350.84 | 1.0899e+08  |           0 |              0 |
| 2025-09-08 00:00:00-04:00 | 354.64 | 358.44 | 344.84 |  346.4  | 7.52083e+07 |           0 |              0 |
| 2025-09-09 00:00:00-04:00 | 348.44 | 350.77 | 343.82 |  346.97 | 5.36899e+07 |           0 |              0 |테슬라의 주가는 한달 전에 비해 올랐습니다. 2025년 8월 11일 종가는 339.03달러였고, 2025년 9월 9일 종가는 346.97달러입니다.

> Finished chain.

In [20]:
response

{'input': [HumanMessage(content='테슬라는 한달 전에 비해 주가가 올랐나 내렸나?', additional_kwargs={}, response_metadata={})],
 'output': '테슬라의 주가는 한달 전에 비해 올랐습니다. 2025년 8월 11일 종가는 339.03달러였고, 2025년 9월 9일 종가는 346.97달러입니다.'}

#### `AgentExecutor`에서 `invoke()`, `stream()` 메서드 차이

* `AgentExecutor`의 `stream()`은 에이전트의 사고 과정을 상세히 보여줌.
* `stream()` 반환 `token`은 `actions`, `observation`, `output` 등 다양한 정보 포함함.
* `invoke()`는 에이전트 실행 후 최종 답변만 반환, 중간 과정은 표시 안 됨.
* `stream()`으로 최종 답변만 원하면 `token` 타입 확인 후 `output` 키 또는 문자열만 추출해야 함.

In [21]:
response = agent_executor.stream({"input": messages})

In [ ]:
next(response)

> Entering new None chain...

{'actions': [ToolAgentAction(tool='get_yf_stock_history', tool_input={'stock_history_input': {'period': '1mo', 'ticker': 'TSLA'}}, log="\nInvoking: `get_yf_stock_history` with `{'stock_history_input': {'period': '1mo', 'ticker': 'TSLA'}}`\n\n\n", message_log=[AIMessageChunk(content='', additional_kwargs={'function_call': {'name': 'get_yf_stock_history', 'arguments': '{"stock_history_input": {"period": "1mo", "ticker": "TSLA"}}'}}, response_metadata={'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash', 'safety_ratings': []}, id='run--1b8ff29a-25ff-4501-a5a1-82b5ae64f276', tool_calls=[{'name': 'get_yf_stock_history', 'args': {'stock_history_input': {'period': '1mo', 'ticker': 'TSLA'}}, 'id': '9c6b85ce-33e4-498c-91f7-2f0ec9cd515e', 'type': 'tool_call'}], usage_metadata={'input_tokens': 303, 'output_tokens': 517, 'total_tokens': 820, 'input_token_details': {'cache_read': 0}, 'output_token_details': {'reasoning': 482}}, tool_call_chunks=[{'name': 'get_yf_stock_history', 'args': '{"stock_history_input": {"period": "1mo", "ticker": "TSLA"}}', 'id': '9c6b85ce-33e4-498c-91f7-2f0ec9cd515e', 'index': None, 'type': 'tool_call_chunk'}])], tool_call_id='9c6b85ce-33e4-498c-91f7-2f0ec9cd515e')],
 'messages': [AIMessageChunk(content='', additional_kwargs={'function_call': {'name': 'get_yf_stock_history', 'arguments': '{"stock_history_input": {"period": "1mo", "ticker": "TSLA"}}'}}, response_metadata={'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash', 'safety_ratings': []}, id='run--1b8ff29a-25ff-4501-a5a1-82b5ae64f276', tool_calls=[{'name': 'get_yf_stock_history', 'args': {'stock_history_input': {'period': '1mo', 'ticker': 'TSLA'}}, 'id': '9c6b85ce-33e4-498c-91f7-2f0ec9cd515e', 'type': 'tool_call'}], usage_metadata={'input_tokens': 303, 'output_tokens': 517, 'total_tokens': 820, 'input_token_details': {'cache_read': 0}, 'output_token_details': {'reasoning': 482}}, tool_call_chunks=[{'name': 'get_yf_stock_history', 'args': '{"stock_history_input": {"period": "1mo", "ticker": "TSLA"}}', 'id': '9c6b85ce-33e4-498c-91f7-2f0ec9cd515e', 'index': None, 'type': 'tool_call_chunk'}])]}