In [1]:
import os
from dotenv import load_dotenv
load_dotenv()

gemini_api_key = os.getenv("GEMINI_API_KEY")

In [13]:
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage

model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", google_api_key=gemini_api_key)

model.invoke([HumanMessage("테슬라는 한달 전에 비해 주가가 올랐나 내렸나?")])

AIMessage(content="죄송합니다만, 저는 실시간 주가 정보를 제공할 수 없습니다. 주가는 매우 유동적이며 실시간으로 변동하기 때문에, 제가 학습한 데이터는 특정 시점까지만 유효합니다.\n\n테슬라(TSLA) 주가가 한 달 전에 비해 올랐는지 내렸는지 확인하시려면, 현재 시점의 금융 정보를 제공하는 웹사이트나 앱을 이용하셔야 합니다.\n\n예를 들어, **구글 파이낸스, 네이버 금융, 카카오 증권, 야후 파이낸스, 인베스팅닷컴** 등에서 'TSLA'를 검색하여 한 달간의 주가 변동을 확인하실 수 있습니다.", additional_kwargs={}, response_metadata={'prompt_feedback': {'block_reason': 0, 'safety_ratings': []}, 'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash', 'safety_ratings': [], 'model_provider': 'google_genai'}, id='lc_run--b5fec759-16ea-4e59-b318-a31712c97271-0', usage_metadata={'input_tokens': 17, 'output_tokens': 680, 'total_tokens': 697, 'input_token_details': {'cache_read': 0}, 'output_token_details': {'reasoning': 535}})

### ⌚시계 도구

In [14]:
from langchain_core.tools import tool
from datetime import datetime
from zoneinfo import ZoneInfo

@tool # @tool 데코레이터를 사용하여 함수를 도구로 등록
def get_current_time(timezone: str, location: str) -> str:
    """ 현재 시각을 반환하는 함수

    Args:
        timezone (str): 타임존 (예: 'Asia/Seoul') 실제 존재하는 타임존이어야 함
        location (str): 지역명. 타임존이 모든 지명에 대응되지 않기 때문에 이후 llm 답변 생성에 사용됨
    """
    target_timezone = ZoneInfo(timezone)
    now = datetime.now(target_timezone).strftime("%Y-%m-%d %H:%M:%S")
    location_and_local_time = f'{timezone} ({location}) 현재시각 {now} ' # 타임존, 지역명, 현재시각을 문자열로 반환
    print(location_and_local_time)
    return location_and_local_time

#### 파이단틱(Pydantic)

*   **데이터 유효성 검사**: 런타임에 데이터 유효성을 강제하여 오류를 조기에 발견하고 안정적인 애플리케이션을 구축할 수 있게 한다. 
*   **설정 관리**: 환경 변수, 파일 등에서 애플리케이션 설정을 로드하고 유효성을 검사하여 안전하고 구성 가능한 애플리케이션을 만들 수 있게 한다.
*   **데이터 직렬화 및 역직렬화**: Python 객체를 JSON과 같은 형식으로 쉽게 변환(직렬화)하고 다시 Python 객체로 역변환(역직렬화)할 수 있게 한다.
*   **문서화**: Pydantic 모델은 OpenAPI(Swagger)와 같은 도구에서 자동으로 API 문서를 생성하는 데 사용될 수 있게 한다.

In [15]:
# 도구의 스키마(schema) 정의, LLM이 정확한 도구 호출 생성 가능
from pydantic import BaseModel, Field

class StockHistoryInput(BaseModel):
    ticker: str = Field(..., title="주식 코드", description="주식 코드 (예: TSLA)")
    period: str = Field(..., title="기간", description="주식 데이터 조회 기간 (예: 1d, 1mo, 1y)")

#### Yahoo Finance API 간단 사용법

In [16]:
import yfinance as yf

# 테슬라 주식 데이터 가져오기
tsla = yf.Ticker("TSLA")

# 1년간의 일별 주가 데이터
hist = tsla.history(period="1y")

In [17]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-11-21 00:00:00-05:00,343.809998,347.989990,335.279999,339.640015,58011700,0.0,0.0
2024-11-22 00:00:00-05:00,341.089996,361.529999,337.700012,352.559998,89140700,0.0,0.0
2024-11-25 00:00:00-05:00,360.140015,361.929993,338.200012,338.589996,95890900,0.0,0.0
2024-11-26 00:00:00-05:00,341.000000,346.959991,335.660004,338.230011,62295900,0.0,0.0
2024-11-27 00:00:00-05:00,341.799988,342.549988,326.589996,332.890015,57896400,0.0,0.0
...,...,...,...,...,...,...,...
2025-11-14 00:00:00-05:00,386.299988,412.190002,382.779999,404.350006,105506700,0.0,0.0
2025-11-17 00:00:00-05:00,398.739990,423.959991,398.739990,408.920013,102214300,0.0,0.0
2025-11-18 00:00:00-05:00,405.380005,408.899994,393.709991,401.250000,80688600,0.0,0.0
2025-11-19 00:00:00-05:00,406.179993,411.779999,398.500000,403.989990,72047700,0.0,0.0
2025-11-20 00:00:00-05:00,414.630005,428.940002,394.739990,395.230011,112812600,0.0,0.0

In [18]:
# 테슬라 주식 데이터 가져오기
tsla = yf.Ticker("TSLA")

# 특정 기간 (예: 2024년 1월 1일 ~ 2월 29일)
start_date = "2025-10-01"
end_date = "2025-10-31"
specific_hist = tsla.history(start=start_date, end=end_date)

In [19]:
specific_hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-10-01 00:00:00-04:00,443.799988,462.290009,440.750000,459.459991,98122300,0.0,0.0
2025-10-02 00:00:00-04:00,470.540009,470.750000,435.570007,436.000000,137009000,0.0,0.0
2025-10-03 00:00:00-04:00,443.290009,446.769989,416.579987,429.829987,133188200,0.0,0.0
2025-10-06 00:00:00-04:00,440.750000,453.549988,436.690002,453.250000,85324900,0.0,0.0
2025-10-07 00:00:00-04:00,447.820007,452.679993,432.450012,433.089996,102296100,0.0,0.0
2025-10-08 00:00:00-04:00,437.570007,441.329987,425.230011,438.690002,71192100,0.0,0.0
2025-10-09 00:00:00-04:00,431.809998,436.350006,426.179993,435.540009,69339900,0.0,0.0
2025-10-10 00:00:00-04:00,436.540009,443.130005,411.450012,413.489990,112107900,0.0,0.0
2025-10-13 00:00:00-04:00,423.529999,436.890015,419.700012,435.899994,79552800,0.0,0.0
2025-10-14 00:00:00-04:00,426.790009,434.200012,417.859985,429.239990,72669400,0.0,0.0
2025-10-15 00:00:00-04:00,434.899994,440.510010,426.329987,435.149994,71558200,0.0,0.0
2025-10-16 00:00:00-04:00,434.730011,439.350006,421.309998,428.750000,77189900,0.0,0.0
2025-10-17 00:00:00-04:00,425.500000,441.459991,423.600006,439.309998,89331600,0.0,0.0
2025-10-20 00:00:00-04:00,443.869995,449.799988,440.609985,447.429993,63719000,0.0,0.0
2025-10-21 00:00:00-04:00,445.760010,449.299988,442.049988,442.600006,54412200,0.0,0.0
2025-10-22 00:00:00-04:00,443.450012,445.540009,429.000000,438.970001,84023500,0.0,0.0
2025-10-23 00:00:00-04:00,420.000000,449.399994,413.899994,448.980011,126709800,0.0,0.0
2025-10-24 00:00:00-04:00,446.829987,451.679993,430.170013,433.720001,94727800,0.0,0.0
2025-10-27 00:00:00-04:00,439.980011,460.160004,438.690002,452.420013,105867500,0.0,0.0
2025-10-28 00:00:00-04:00,454.779999,467.000000,451.600006,460.549988,80185700,0.0,0.0
2025-10-29 00:00:00-04:00,462.500000,465.700012,452.649994,461.510010,67983500,0.0,0.0
2025-10-30 00:00:00-04:00,451.049988,455.059998,439.609985,440.100006,72447900,0.0,0.0

In [20]:
print(specific_hist.to_markdown())

| Date                      |   Open |   High |    Low |   Close |      Volume |   Dividends |   Stock Splits |
|:--------------------------|-------:|-------:|-------:|--------:|------------:|------------:|---------------:|
| 2025-10-01 00:00:00-04:00 | 443.8  | 462.29 | 440.75 |  459.46 | 9.81223e+07 |           0 |              0 |
| 2025-10-02 00:00:00-04:00 | 470.54 | 470.75 | 435.57 |  436    | 1.37009e+08 |           0 |              0 |
| 2025-10-03 00:00:00-04:00 | 443.29 | 446.77 | 416.58 |  429.83 | 1.33188e+08 |           0 |              0 |
| 2025-10-06 00:00:00-04:00 | 440.75 | 453.55 | 436.69 |  453.25 | 8.53249e+07 |           0 |              0 |
| 2025-10-07 00:00:00-04:00 | 447.82 | 452.68 | 432.45 |  433.09 | 1.02296e+08 |           0 |              0 |
| 2025-10-08 00:00:00-04:00 | 437.57 | 441.33 | 425.23 |  438.69 | 7.11921e+07 |           0 |              0 |
| 2025-10-09 00:00:00-04:00 | 431.81 | 436.35 | 426.18 |  435.54 | 6.93399e+07 |           0 |              0 |
| 2025-10-10 00:00:00-04:00 | 436.54 | 443.13 | 411.45 |  413.49 | 1.12108e+08 |           0 |              0 |
| 2025-10-13 00:00:00-04:00 | 423.53 | 436.89 | 419.7  |  435.9  | 7.95528e+07 |           0 |              0 |
| 2025-10-14 00:00:00-04:00 | 426.79 | 434.2  | 417.86 |  429.24 | 7.26694e+07 |           0 |              0 |
| 2025-10-15 00:00:00-04:00 | 434.9  | 440.51 | 426.33 |  435.15 | 7.15582e+07 |           0 |              0 |
| 2025-10-16 00:00:00-04:00 | 434.73 | 439.35 | 421.31 |  428.75 | 7.71899e+07 |           0 |              0 |
| 2025-10-17 00:00:00-04:00 | 425.5  | 441.46 | 423.6  |  439.31 | 8.93316e+07 |           0 |              0 |
| 2025-10-20 00:00:00-04:00 | 443.87 | 449.8  | 440.61 |  447.43 | 6.3719e+07  |           0 |              0 |
| 2025-10-21 00:00:00-04:00 | 445.76 | 449.3  | 442.05 |  442.6  | 5.44122e+07 |           0 |              0 |
| 2025-10-22 00:00:00-04:00 | 443.45 | 445.54 | 429    |  438.97 | 8.40235e+07 |           0 |              0 |
| 2025-10-23 00:00:00-04:00 | 420    | 449.4  | 413.9  |  448.98 | 1.2671e+08  |           0 |              0 |
| 2025-10-24 00:00:00-04:00 | 446.83 | 451.68 | 430.17 |  433.72 | 9.47278e+07 |           0 |              0 |
| 2025-10-27 00:00:00-04:00 | 439.98 | 460.16 | 438.69 |  452.42 | 1.05868e+08 |           0 |              0 |
| 2025-10-28 00:00:00-04:00 | 454.78 | 467    | 451.6  |  460.55 | 8.01857e+07 |           0 |              0 |
| 2025-10-29 00:00:00-04:00 | 462.5  | 465.7  | 452.65 |  461.51 | 6.79835e+07 |           0 |              0 |
| 2025-10-30 00:00:00-04:00 | 451.05 | 455.06 | 439.61 |  440.1  | 7.24479e+07 |           0 |              0 |

### 📈 주식 종목 가격 조회 도구

In [21]:
@tool
def get_yf_stock_history(stock_history_input: StockHistoryInput) -> str:
    """ 주식 종목의 가격 데이터를 조회하는 함수"""
    stock = yf.Ticker(stock_history_input.ticker)
    history = stock.history(period=stock_history_input.period)
    history_md = history.to_markdown() 

    return history_md

In [22]:
from dataclasses import dataclass

@dataclass
class UserContext:
    user_id: str

In [23]:
# create_tool_calling_agent: 도구 호출 기능이 있는 에이전트를 생성하는 함수
# AgentExecutor: 생성된 에이전트의 실행을 담당하는 클래스
from langchain.agents import create_agent
from langchain.tools import tool, ToolRuntime
from langchain_core.prompts import ChatPromptTemplate

# 도구들을 tools 리스트에 추가
tools = [get_current_time, get_yf_stock_history]

# 에이전트 생성
agent = create_agent(
    model,
    tools=tools,
    context_schema=UserContext,
    system_prompt="너는 사용자의 질문에 답변을 하기 위해 tools를 사용할 수 있다."
)

In [24]:
result = agent.invoke(
    {"messages": [{"role": "user", "content": "테슬라는 한달 전에 비해 주가가 올랐나 내렸나?"}]},
    context=UserContext(user_id="user123")
)

In [25]:
result

{'messages': [HumanMessage(content='테슬라는 한달 전에 비해 주가가 올랐나 내렸나?', additional_kwargs={}, response_metadata={}, id='f6f40492-e635-4362-9b2d-8613d93759e5'),
  AIMessage(content='', additional_kwargs={'function_call': {'name': 'get_yf_stock_history', 'arguments': '{"stock_history_input": {"period": "1mo", "ticker": "TSLA"}}'}, '__gemini_function_call_thought_signatures__': {'b44c3c8f-99bd-4e2a-b358-7d8cabc6cfd8': 'Co0FAdHtim+h1tb71pyOOzjvcwdeA/6kttYxxy1yWO2cyD4PyCCpMMnPowKL/TameRvCoONSyXsAd6DM7Z20FP+hx+OH8alCbD2ODYVTWnptEbvV/SZFpCLASYtzm+WjpN5LuqrNdzsMOVyQoW78XoCsGtk6w5RlC4lG9/k7+BMw2riNlvobhTYgstPKVQMVbvOqWhu6DyESTbbstr0SoK25DXmfxhZ48TgXluBa7EGGtZeb/AWZtg74RoUNw5kpc97bVfNsM0BD0Y4hkBZEgEq/XkAptwnlS13QfMzts6iN1fICCshu4SHqT3WzWnvyvDLUrS5s37hMSxmCZKJHmyfXcKV2S2cZMinVLNJIurTSPOWJc0XPA5P7h4z5sfTdAtGhGmqRXx1hueQxNSCTGEddxBZ1jKKfVQ+42OgXQB4GNtQpUINjM9IIz18iCa0+5Ajeg8I2U33g043jUyAIqnFL/5lerfOq2KtczZhMTbjxve0WjZUxsjf7Tb22isGQczyEQNRmeDQA09Ca7HGQ+xovYb0VxWJfqfMsy5o33h6QiZLTOZ88LE2e+qD1608BIcicIPy+Jb5QAxZGdUnAocUC1Of8rmX2+Npz3k5Zm6xn57nVFl4phqAN/EoHzLeeBb0KgJJ8cUsaG8xxsEG7Cae+c4t9ZG9XZtLpDi9+/M8bcf8aIpi7Ub1lFPkY5bhyDiBQ+1x9z8k4aJJX/AiJ75cg2kL0o6Lg1NQAUG9pUhwTSamKGtX/UosbOvm+2nPtpVkByzlpZjzE1SlXtTwLUT1Yp11f67cJH6QW/K4C9z7zG3OVHPkJIPHr1Jf8vavF5xNZKf2TKh5lHVsJQkIAkSkpvyBxXSOnPAYVstbKUnY='}}, response_metadata={'prompt_feedback': {'block_reason': 0, 'safety_ratings': []}, 'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash', 'safety_ratings': [], 'model_provider': 'google_genai'}, id='lc_run--cfd16900-44cc-434e-a41f-a7838ff78550-0', tool_calls=[{'name': 'get_yf_stock_history', 'args': {'stock_history_input': {'period': '1mo', 'ticker': 'TSLA'}}, 'id': 'b44c3c8f-99bd-4e2a-b358-7d8cabc6cfd8', 'type': 'tool_call'}], usage_metadata={'input_tokens': 288, 'output_tokens': 204, 'total_tokens': 492, 'input_token_details': {'cache_read': 0}, 'output_token_details': {'reasoning': 169}}),
  ToolMessage(content='| Date                      |   Open |   High |    Low |   Close |      Volume |   Dividends |   Stock Splits |\n|:--------------------------|-------:|-------:|-------:|--------:|------------:|------------:|---------------:|\n| 2025-10-21 00:00:00-04:00 | 445.76 | 449.3  | 442.05 |  442.6  | 5.44122e+07 |           0 |              0 |\n| 2025-10-22 00:00:00-04:00 | 443.45 | 445.54 | 429    |  438.97 | 8.40235e+07 |           0 |              0 |\n| 2025-10-23 00:00:00-04:00 | 420    | 449.4  | 413.9  |  448.98 | 1.2671e+08  |           0 |              0 |\n| 2025-10-24 00:00:00-04:00 | 446.83 | 451.68 | 430.17 |  433.72 | 9.47278e+07 |           0 |              0 |\n| 2025-10-27 00:00:00-04:00 | 439.98 | 460.16 | 438.69 |  452.42 | 1.05868e+08 |           0 |              0 |\n| 2025-10-28 00:00:00-04:00 | 454.78 | 467    | 451.6  |  460.55 | 8.01857e+07 |           0 |              0 |\n| 2025-10-29 00:00:00-04:00 | 462.5  | 465.7  | 452.65 |  461.51 | 6.79835e+07 |           0 |              0 |\n| 2025-10-30 00:00:00-04:00 | 451.05 | 455.06 | 439.61 |  440.1  | 7.24479e+07 |           0 |              0 |\n| 2025-10-31 00:00:00-04:00 | 446.75 | 458    | 443.69 |  456.56 | 8.31358e+07 |           0 |              0 |\n| 2025-11-03 00:00:00-05:00 | 455.99 | 474.07 | 453.8  |  468.37 | 8.45952e+07 |           0 |              0 |\n| 2025-11-04 00:00:00-05:00 | 454.46 | 460.22 | 443.6  |  444.26 | 8.77566e+07 |           0 |              0 |\n| 2025-11-05 00:00:00-05:00 | 452.05 | 466.33 | 440.71 |  462.07 | 8.5573e+07  |           0 |              0 |\n| 2025-11-06 00:00:00-05:00 | 461.96 | 467.45 | 435.09 |  445.91 | 1.09623e+08 |           0 |              0 |\n| 2025-11-07 00:00:00-05:00 | 437.92 | 439.36 | 421.88 |  429.52 | 1.03472e+08 |           0 |              0 |\n| 2025-11-10 00:00:00-05:00 | 439.6  | 449.67 | 433.36 |  445.23 | 7.65159e+07 |           0 |              0 |\n| 2025-11-11 00:00:00-05:00 | 439.4  | 442.49 | 432.36 |  439.62 | 6.05332e+07 |           0 |              0 |\n| 2025-11-12 00:00:00-05:00 | 442.15 | 442.33 | 426.56 |  430.6  | 5.85135e+07 |           0 |              0 |\n| 2025-11-13 00:00:00-05:00 | 423.13 | 424.5  | 396.34 |  401.99 | 1.18948e+08 |           0 |              0 |\n| 2025-11-14 00:00:00-05:00 | 386.3  | 412.19 | 382.78 |  404.35 | 1.05507e+08 |           0 |              0 |\n| 2025-11-17 00:00:00-05:00 | 398.74 | 423.96 | 398.74 |  408.92 | 1.02214e+08 |           0 |              0 |\n| 2025-11-18 00:00:00-05:00 | 405.38 | 408.9  | 393.71 |  401.25 | 8.06886e+07 |           0 |              0 |\n| 2025-11-19 00:00:00-05:00 | 406.18 | 411.78 | 398.5  |  403.99 | 7.20477e+07 |           0 |              0 |\n| 2025-11-20 00:00:00-05:00 | 414.63 | 428.94 | 394.74 |  395.23 | 1.12813e+08 |           0 |              0 |', name='get_yf_stock_history', id='56082654-5107-4f04-8d26-5eee1e27d5ce', tool_call_id='b44c3c8f-99bd-4e2a-b358-7d8cabc6cfd8'),
  AIMessage(content=[{'type': 'text', 'text': '테슬라의 주가는 한달 전에 비해 **내렸습니다.**\n\n한달 전인 2025년 10월 21일의 종가는 442.60이었으나, 가장 최근인 2025년 11월 20일의 종가는 395.23으로 하락했습니다.', 'extras': {'signature': 'CpIGAdHtim+o6WWeagwQ4ApVq4P5TdtCqVtZ50sRA1wdWPg5JkMdNuuItrSVXWwQm8cUROhis8QrzU6Fyj9atsv6CHCHuZCvaS8B0H6sc2956+wYr49tMIBtt0g9TWjaAHpgcs1SUvAWu4cs+6i/lUPVUNi2STz3Fd9zKxhyZX8LTttmTFz45wAEY2CO6umHNyHGp3QgAAvQA/21hN5KT4rdknStYpFysdLTQMWmyzlay8WDQAPMyLnZ1sXW20WMa4jB+I7enjd7B1uqGDT4bSWXnfPa+39KS+WUlpvDwsloRV5eze51QThbu6O97F3u0ff8nqDxpPVqZNqKl1uDOMQi+QvPWNq1C4NgFPwXspAf7GWrJqZdKpsZD5MUwRT4LsTPYcFszDGsYcsHgWRRn3VBZjdvG7vcMRXOpOltDToZ4r7EyRr/pBbkEZmFKlGfpBfrbGNGeB3RlRJN8D1JsGM9kQs8uWhXP3fzxvMllhyJZWW0GYifLsRbarBECtE5q/CAWrQDLBaWwi31IlSQJSF0smxvsdXdS2W7E9yVWJmrqcASZUxeI+il7Y4p7wn3pzWsyuUWMEG5CSGhn57nY3gHW3D2IEw/JGc19O6gDCVEU2nRKcMgqu77zabGHg+c4Nssvho39Xh2D0R2OvTjs/7AILiepPI1G7UG/Daz6V1JtMLNL96xxr+wiQsKHe9CoeZ6ZxC5SJBLv+BImSbSXWWybAg5dXRJnf6ZuR1OQLvezuAJikwJd3JoYdji0R/yi9kf5oEiWiPeSSQEUVmMT88FHzVTljj9YZ0ckSrufm0SJ+ZncUyHdFORsyKEoRJIW1UuN5VnCRXrseO7Vfs+g4AwJY2mzDBsVxs6ooyktaaiwlnpElwMSyHMluxFlzQoBCiUSvTH7dFNLQAZxlG5gx2YMbFiFn8nW29lCpkdD8V2FgADR62I1nzCpnFB/1Y5jCtdhoKi0APt/b1lh2VbbTOKn34WkxCDPGJjWDExF/f/btRso4lbixcg/bZ+9pAbE358M9r8XCvTz0ji+h7pgZpKPWxQ'}}], additional_kwargs={}, response_metadata={'prompt_feedback': {'block_reason': 0, 'safety_ratings': []}, 'finish_reason': 'STOP', 'model_name': 'gemini-2.5-flash', 'safety_ratings': [], 'model_provider': 'google_genai'}, id='lc_run--6644d060-5bed-4f6d-9982-a4ebe0892759-0', usage_metadata={'input_tokens': 2220, 'output_tokens': 299, 'total_tokens': 2519, 'input_token_details': {'cache_read': 0}, 'output_token_details': {'reasoning': 220}})]}